<h3>Capacitaciones</h3>
<div class="col-sm-9">
    <div>
        <a class="btn btn-sm btn-primary" href="<?php echo BASE_URL ?>/administracion/capacitacion/nuevo"><span class="glyphicon glyphicon-plus-sign"></span> Nueva Capacitación
        </a>
    </div>
    <br/>
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableCapacitacion" class="table table-striped table-bordered bootstrap-datatable datatable dataTable" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th>Título</th>
            <th>Fecha Registro</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php
                foreach ($this->capacitacion as $capacitacion) {
                    $fechaRegistro = new Zend_Date($capacitacion['capacitacion_fecha_registro']);
                    ?>
                    <tr>
                        <td><?php echo $capacitacion['capacitacion_titulo']; ?></td>
                        <td><?php echo $fechaRegistro->get('dd-MM-YYYY'); ?></td>
                        <td><?php
                            if ($capacitacion['swt_activo'])
                                echo '<span class="label label-success">Activo</span>';
                            else
                                echo '<span class="label label-warning">Finalizado</span>';
                            ?>
                        </td>
                        <td>
                            <a class="btn btn-success btn-sm" href="<?php echo BASE_URL; ?>/centro-formacion/capacitacion/taller/<?php echo $capacitacion['capacitacion_id']; ?>" target="_blank"><span class="glyphicon glyphicon-eye-open"></span> Ver</a>
                            <a class="btn btn-info btn-sm" href="<?php echo BASE_URL; ?>/administracion/capacitacion/editar/id/<?php echo $capacitacion['capacitacion_id']; ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                            
                            <a class="btn btn-danger btn-sm" href="<?php echo BASE_URL; ?>/administracion/capacitacion/eliminar/id/<?php echo $capacitacion['capacitacion_id']; ?>"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
