
<h3><span class="glyphicon glyphicon-inbox"></span> Nueva Capacitación</h3>
<br/>
<form id="frmCapacitacion" enctype='multipart/form-data' class="form-horizontal" role="form" method="post" action="">
    <fieldset>
        <div class="col-sm-4 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Título
                </span>
                <?php echo $this->form->getElement('titulo'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-3 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Fecha
                </span>
                <?php echo $this->form->getElement('fecha'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-3 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Trainer
                </span>
                <?php echo $this->form->getElement('trainer'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6 margin-bottom-20">
            <div class="input-group">
                <span class="input-group-addon" style="border-right: 1px solid #999999">
                    Imagen
                </span>
                <?php echo $this->form->getElement('file'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6 margin-bottom-20">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li class="active"><a href="#tabPresentacion" role="tab" data-toggle="tab">Presentación</a></li>
                <li><a href="#tabBeneficios" role="tab" data-toggle="tab">Beneficios</a></li>
                <li><a href="#tabContenido" role="tab" data-toggle="tab">Contenido</a></li>
                <li><a href="#tabInfo" role="tab" data-toggle="tab">Información General</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <input type="hidden" name="txtPresentacion" id="txtPresentacion" />
                <input type="hidden" name="txtBeneficios" id="txtBeneficios" />
                <input type="hidden" name="txtContenido" id="txtContenido" />
                <input type="hidden" name="txtInfo" id="txtInfo" />
                <div class="tab-pane active" id="tabPresentacion">
                    <div class="summernote" id="presentacion"></div>
                </div>
                <div class="tab-pane " id="tabBeneficios">
                    <div class="summernote" id="beneficios"></div>
                </div>
                <div class="tab-pane " id="tabContenido">
                    <div class="summernote" id="contenido"></div>
                </div>
                <div class="tab-pane " id="tabInfo">
                    <div class="summernote" id="info"></div>
                </div>
            </div>        
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-6 margin-bottom-20">
            <div class="input-group">
                <span class="input-group-addon" style="border-right: 1px solid #999999">
                    ¿Quiénes deben asisitir?
                </span>
                <?php echo $this->form->getElement('asiste'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-3">
            <button class="btn btn-primary btnRegistrar" type="submit">Registrar</button>
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>/administracion/capacitacion/">Cancelar</a>
        </div>
    </fieldset>
</form>
<script>

</script>