<div style="margin-top: 20px;font-size: 13px" class="container">
    <div class="col-md-12">
        <h1>¡Bienvenido a CEMACC!</h1>
        <br/>
        <h4>Estimado(a) cliente. Gracias por registrarse en nuestro sistema. Las contraseñas de cada usuario registrado será enviada
            al correo ingresado previamente. Puede ingresar al sistema haciendo click al siguiente <a href="<?php echo BASE_URL.'/login'; ?>"> LINK</a></h4>
    </div>
</div>    
