<h4> <span class="glyphicon glyphicon-user"></span> Editar Paquete</h4>
<br/>

<form class="form-horizontal" role="form" method="post" action="">
     <?php echo $this->form->getElement('paquete'); ?>
    <div class="col-md-3 margin-bottom-10">     
        <div class="input-group">
            <span class="input-group-addon">
                Nombre
            </span>
            <?php echo $this->form->getElement('nombre'); ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-2 margin-bottom-10">     
        <div class="input-group">
            <span class="input-group-addon">
                Días
            </span>    
            <?php echo $this->form->getElement('dias'); ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-2 margin-bottom-10">     
        <div class="input-group">
            <span class="input-group-addon">
                Precio
            </span>
            <?php echo $this->form->getElement('precio'); ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-2 margin-bottom-10">     
        <div class="input-group">
            <span class="input-group-addon">
                Dimensión
            </span>
            <?php echo $this->form->getElement('dimension'); ?>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-5 margin-bottom-10">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>

</form>

