<h4> <span class="glyphicon glyphicon-user"></span> Editar Empresa</h4>
<div class="col-md-8">
    <br/>

    <form class="form-horizontal" role="form" method="post" action="">

        <?php echo $this->form->getElement('empresa'); ?>
        <?php echo $this->form->getElement('ubicacion'); ?>
        <?php echo $this->form->getElement('ubigeo'); ?>
        <div class="col-md-4 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    RUC
                </span>
                <?php echo $this->form->getElement('numeroRuc'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-6 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    Nombre Comercial
                </span>    
                <?php echo $this->form->getElement('nombreComercial'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-6 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    Razón Social
                </span>
                <?php echo $this->form->getElement('razonSocial'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-5 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    Categoría
                </span>
                <?php echo $this->form->getElement('categoria'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-5 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    SubCategoría
                </span>
                <?php echo $this->form->getElement('subcategoria'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    País
                </span>
                <?php echo $this->form->getElement('pais'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    Departamento
                </span>
                <?php echo $this->form->getElement('departamento'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    Provincia
                </span>
                <?php echo $this->form->getElement('provincia'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 margin-bottom-10">     
            <div class="input-group">
                <span class="input-group-addon">
                    Distrito
                </span>
                <?php echo $this->form->getElement('distrito'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-6 margin-bottom-20">     
            <div class="input-group">
                <span class="input-group-addon">
                    Dirección
                </span>
                <?php echo $this->form->getElement('direccion'); ?>
            </div>
        </div>         
        <div class="clearfix"></div>
        <div class="col-md-5 margin-bottom-10">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>

    </form>

</div>
