<h3>Listado de Empresas</h3>
<div class="box-content col-sm-10">
    <div>
        <a class="btn btn-sm btn-primary" href="<?php echo BASE_URL; ?>/administracion/empresa/nuevo"><span class="glyphicon glyphicon-plus-sign"></span> Nuevo Pre-Registro
        </a>
    </div>
    <br/>
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableEmpresa" class="table table-striped table-bordered bootstrap-datatable datatable dataTable table-hover" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th>RUC</th>
            <th>Nombre Comercial</th>
            <th>Razón Social</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php
                foreach ($this->empresa as $data) {
                    ?>
                    <tr>
                        <td><?php echo $data['empresa_ruc']; ?></td>
                        <td><?php echo $data['empresa_nombre_comercial']; ?></td>
                        <td><?php echo $data['empresa_razon_social']; ?></td>
                        <td><?php
                            if ($data['swt_activo'])
                                echo '<span class="label label-success">Registrado</span>';
                            else
                                echo '<span class="label label-warning">Pre-Inscripción</span>';
                            ?>
                        </td>
                        <td>
                            <a class="btn btn-success btn-sm" href="<?php echo BASE_URL; ?>/directorio/empresa/id/<?php echo $data['empresa_id']; ?>" target="_blank"><span class="glyphicon glyphicon-eye-open"></span> Ver</a>
                            <a class="btn btn-info btn-sm" href="<?php echo BASE_URL; ?>/administracion/empresa/editar/id/<?php echo $data['empresa_id']; ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                            <?php if ($data['swt_activo']) { ?>
                                <a class="btn btn-danger btn-sm" href="<?php echo BASE_URL; ?>/administracion/empresa/activar/id/<?php echo $data['empresa_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                            <?php } else { ?>
                                <a class="btn btn-warning btn-sm" href="<?php echo BASE_URL; ?>/administracion/empresa/activar/id/<?php echo $data['empresa_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
