<div class="box-content" style="display: block;">
    <div>
        <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-distrito-judicial-nuevo')) { ?>
            <a class="btn btn-small btn-primary" href="/administracion/distrito-judicial/nuevo"><i class="icon-plus-sign icon-white"></i>Agregar Nuevo Distrito Judicial</a>
        <?php } ?>
    </div>
    <br/>
    <?php if(count($this->listAll)>0){ ?>
    <div>
        <table id="tableAccesorios" class="table table-striped  table-hover dataTable">
            <thead>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php foreach ($this->listAll as $index): ?>
                    <tr>
                        <td><?php echo $index['distrito_judicial_nombre']; ?></td>
                        <td>
                            <?php if ($index['distrito_judicial_flag_activo']) { ?>
                            <span class="label label-success">Activo</span>
                            <?php } else { ?>
                                <span class="label label-danger">Inactivo</span>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-distrito-judicial-editar')) { ?>
                            <a class="btn btn-info" href="/administracion/distrito-judicial/editar/id/<?php echo $index['distrito_judicial_id']; ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                            <?php } ?>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-distrito-judicial-activar')) { ?>
                                <?php if ($index['distrito_judicial_flag_activo']) { ?>
                                    <a class="btn btn-danger" href="/administracion/distrito-judicial/activar/id/<?php echo $index['distrito_judicial_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                                <?php } else { ?>
                                    <a class="btn btn-success" href="/administracion/distrito-judicial/activar/id/<?php echo $index['distrito_judicial_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                                <?php } ?>
                            <?php } ?>
                        </td>
                    </tr>

                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php } else { ?>
    <div>No Hay datos registrados</div>
    <?php }  ?>
</div>
