<h3>Agregar Sede</h3>
<div class="box-content" style="display: block;">
    <hr>
    <div class="col-lg-6">
        <form action="" method="POST">
            <?php echo $this->form->getElement('sede_id'); ?>
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Nombre:</span>
                    <?php echo $this->form->getElement('nombre'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Especialidad:</span>
                    <?php echo $this->form->getElement('especialidad'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Dirección:</span>
                    <?php echo $this->form->getElement('direccion'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <button type="submit" class="btn btn-primary">Actualizar Sede</button>
                <a class="btn btn-default" href="/administracion/sede" >Cancelar</a>
            </div>    
        </form>
    </div>
</div>
