<!--<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
var map;
function initialize() {
   
var myLatlng = new google.maps.LatLng(-12.066821,-77.037915);
  var mapOptions = {
    zoom: 18,
    center: myLatlng
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
      
      
  var contentString = '<div id="content">'+
      '<div id="siteNotice">'+
      '</div>'+
      '<h4 id="firstHeading" class="">BitMinds Consultors</h4>'+
      '<div id="bodyContent">'+
      '<p><b>Direccion:</b> Av. República de Chile N° 271 <br>Oficina 301 - Lima Cercado'+
      '</p>'+
      '<p><b>Telefono:</b> 511-6372624 '+
      '</p>'+
      
      '</div>'+
      '</div>';
      var infowindow = new google.maps.InfoWindow({
      content: contentString
  });
  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'BitMinds Consultors'
  });
  google.maps.event.addListener(marker, 'click', function() {
    infowindow.open(map,marker);
  });
  google.maps.event.addListener(marker, 'mouseover', function() {
    infowindow.open(map,marker);
  });
      
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>-->
<div style="margin-top: 20px;font-size: 13px" class="container">
    <div class="col-md-7">
        <ul class="media-list">
            <li class="media">

                <div class="media-body">
                    <h4 class="media-heading">CONTACTO</h4>
                    <p>Telefono: 051 - 6062473</p>
                    <p>Email: info@cem-acc.com</p>
                    <p>Dirección: Centro Empresarial ICONO Miraflores • Av. 2 de Mayo 516 Of. 201, Miraflores</p>
                </div>
            </li>
        </ul>
<!--<div id="map-canvas" style="width: 100%; height: 250px"></div>-->
<div><img src="<?php echo STATIC_URL. '/img/contacto.jpg'; ?>" alt=""  width="500"/></div>
    </div>
    <div class="col-md-5">
        <ul class="media-list">
            <li class="media">
                <div class="media-body">
                    <h4 class="media-heading">FORMULARIO DE CONTACTO</h4>
                    <form class="form-horizontal margin_top_20" role="form">
                        <div class="form-group">
                            <label for="nombre" class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nombre" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="email" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="asunto" class="col-sm-2 control-label">Asunto</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="asunto" placeholder="">
                            </div>
                        </div>
                        <div class="form-group">
                        <label for="mensaje" class="col-sm-2 control-label">Mensaje</label>
                            <div class="col-sm-10">
                            <textarea class="form-control" id="mensaje" rows="7"></textarea>
                            </div>
                            </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Enviar</button>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </li>
        </ul>

    </div>
</div>