<h3><span class="glyphicon glyphicon-inbox"></span> Adquirir Productos</h3>
<br/>
<form class="form-horizontal" role="form" method="post" action="">
    <input type="hidden" name="dataProducto" id="dataProducto" />
    <input type="hidden" name="empresaEnvio" id="empresaEnvio" />
    <input type="hidden" name="tblHtml" id="tblHtml" />
    <fieldset>
        <div>
            <button  class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modalAgregarProducto"><span class="glyphicon glyphicon-plus-sign"></span> Agregar Producto
            </button>
        </div>
        <div class="clearfix"></div>
        <br/>
        <div id="dvProductos" class="dataTables_wrapper col-sm-8">
            <table id="tblProductos" class="table table-striped table-bordered table-hover">
                <thead>
                <th width="5%">Nro</th>
                <th width="40%">Nombre del Producto</th>
                <th width="45%">Descripción</th>
                <th width="5%">Cantidad</th>
                <th width="5%">Valor Referencial</th>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div class="clearfix"></div>
        <br/>
        <div class="col-sm-3">
            <div class="input-group">
                <span class="input-group-addon">
                    Enviar a Empresas de
                </span>
                <?php echo $this->form->getElement('categoria'); ?>
            </div>
        </div>
        <div class="col-sm-2">
            <button id="btnAgregarCategoria" class="btn btn-primary" title="Agregar" type="button">+</button>
        </div>

        <div class="col-sm-3">
            <div class="input-group">
                <span class="input-group-addon">
                    Fecha Límite de Cotización
                </span>
                <?php echo $this->form->getElement('fechaLimite'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <br/>
         <div id="dvCategoria" class="col-sm-3">
           
        </div>
        <div class="clearfix"></div>
        <br/>
        <br/>
        <div class="form-group">
            <div class="col-sm-offset-6">
                <a class="btn btn-default" href="/logistica/adquisicion/">Cancelar</a>
                <button class="btn btn-primary" type="submit" id="btnEnviar" >Enviar</button>
            </div>
        </div>
    </fieldset>
</form>

<!-- Modal -->
<div class="modal fade" id="modalAgregarProducto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Agregar Producto</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="frmAgregarProducto" role="form" method="post" action="">
                    <fieldset>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Nombre
                                </span>
                                <?php echo $this->form->getElement('nombre'); ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-sm-8">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Descripción
                                </span>
                                <?php echo $this->form->getElement('descripcion'); ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-sm-4">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Cantidad
                                </span>
                                <?php echo $this->form->getElement('cantidad'); ?>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Precio Referencial
                                </span>
                                <?php echo $this->form->getElement('precio'); ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                    </fieldset>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="submit" id="btnAgregarProducto" class="btn btn-primary">Agregar</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->