<head>
    <?php echo $this->headTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/jqueryui/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/carousel.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/signin.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/margin-padding.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/main.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/flexslider.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/nivo-slider.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/application/css/custom.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/css/font-awesome.min.css" rel="stylesheet" media="screen">
</head>