<head>
    <?php echo $this->headTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link href="<?php echo STATIC_URL; ?>/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/main.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/simple-sidebar.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/navbar-fixed-top.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/margin-padding.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/jqueryui/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo STATIC_URL; ?>/css/summernote.css" rel="stylesheet" media="screen">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <link href="<?php echo STATIC_URL; ?>/application/css/custom_system.css" rel="stylesheet" media="screen">
</head>