<script src="<?php echo STATIC_URL ?>/js/jquery-1.11.0.min.js"></script>
<script src="<?php echo STATIC_URL ?>/js/jquery.dataTables.min.js"></script>
<script src="<?php echo STATIC_URL ?>/js/bootstrap.min.js"></script>
<script src="<?php echo STATIC_URL ?>/jqueryui/jquery-ui-1.10.3.custom.min.js"></script>
<script src="<?php echo STATIC_URL ?>/js/bootstrap.file-input.js"></script>
<script src="<?php echo STATIC_URL ?>/js/summernote.min.js"></script>
<script src="<?php echo STATIC_URL ?>/js/cemacc.js"></script>
<script>
    $.datepicker.regional['es'] = {
        closeText: 'Cerrar',
        prevText: '&#x3c;Ant',
        nextText: 'Sig&#x3e;',
        currentText: 'Hoy',
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
            'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
            'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Mi&eacute;rcoles', 'Jueves', 'Viernes', 'S&aacute;bado'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mi&eacute;', 'Juv', 'Vie', 'S&aacute;b'],
        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'S&aacute;'],
        weekHeader: 'Sm',
        dateFormat: 'dd/mm/yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''};
    $.datepicker.setDefaults($.datepicker.regional['es']);
</script>
