<div class="box-content" style="display: block;">
    <div>
        <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-role-nuevo')) { ?>
            <a class="btn btn-small btn-primary" href="/administracion/role/nuevo"><i class="icon-plus-sign icon-white"></i>Agregar Nuevo Rol</a>
        <?php } ?>
    </div>
    <br/>
    <div id="TableAccesorios_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableAccesorios" class="table table-striped table-bordered bootstrap-datatable datatable dataTable" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Permisos</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php foreach ($this->listRole as $index): ?>
                    <tr>
                        <td><?php echo $index['role_nombre']; ?></td>
                        <td><?php echo $index['role_descripcion']; ?></td>
                        <th><a href="#" class="verPermisos" role="<?php echo $index['role_id']; ?>" >Ver Permisos</a></th>
                        <td>
                            <?php if ($index['role_activo']) { ?>
                            <span class="label label-success">Activo</span>
                            <?php } else { ?>
                                <span class="label label-important">Desactivado</span>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-role-editar')) { ?>
                                <a class="btn btn-info" href="/administracion/role/editar/id/<?php echo $index['role_id']; ?>"><i class="icon-edit icon-white"></i> Editar</a>
                            <?php } ?>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-role-activar')) { ?>
                                <?php if ($index['role_activo']) { ?>
                                    <a class="btn btn-warning" href="/administracion/role/activar/id/<?php echo $index['role_id']; ?>/flag/0"><i class="icon-ban-circle icon-white"></i> Desactivar</a>
                                <?php } else { ?>
                                    <a class="btn btn-warning" href="/administracion/role/activar/id/<?php echo $index['role_id']; ?>/flag/1"><i class="icon-ok-circle icon-white"></i> Activar</a>
                                <?php } ?>
                            <?php } ?>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-role-eliminar')) { ?>
                                <a title="Eliminar Rol" class="btn btn-danger" href="/administracion/role/eliminar/id/<?php echo $index['role_id']; ?>"><i class="icon-trash icon-white"></i> Eliminar</a>
                            <?php } ?>
                        </td>
                    </tr>

                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div class="modal hide fade" id="modalPermisos">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Permisos</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Cerrar</a>
    </div>
</div>