<!DOCTYPE html>
<html lang="en">
    <?php echo $this->render('render/head.phtml') ?>
    <body>
        <input type="hidden" id="dir-static" value="<?php echo STATIC_URL; ?>">
        <!-- topbar starts -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo BASE_URL ?>"><img alt="SKBERGE" src="<?php echo STATIC_URL; ?>/img/logoskberge.jpg"/></a>
                    <!-- user dropdown starts -->
                    <!-- user dropdown ends -->
                    <div class="top-nav nav-collapse">
                        <!--                        <ul class="nav">
                                                    <li><a href="<?php echo BASE_URL ?>">Inicio</a></li>
                                                    <li><a href="<?php echo BASE_URL ?>">Administrador</a></li>
                                                    <li><a href="<?php echo BASE_URL ?>">Dealer</a></li>
                                                    
                                                </ul>-->
                    </div>

                </div>
            </div>
        </div>
        <!-- topbar ends -->
        <div class="container-fluid">
            <div class="row-fluid">
                <!-- left menu starts -->
                <!-- left menu ends -->
                <noscript>
                <div class="alert alert-block span10">
                    <h4 class="alert-heading">Warning!</h4>
                    <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
                </div>
                </noscript>
                <div id="content" class="span10">
                    <div>
                        <ul class="breadcrumb">
                            <li>
                                <?php echo $this->navigation()
                                        ->breadcrumbs()
                                        ->setLinkLast(true)                   // link last page
                                        ->setMaxDepth(1)                      // stop at level 1
                                        ->setSeparator(' <span class="divider"> ▶ </span></li><li>' . PHP_EOL); ?>
                            </li>
                        </ul>
                        
                    
                        <div class="">
                            <div class="box span12">
                                <div class="box-header well">
                                    <h2><script type="text/javascript">
                                        document.write(document.title);
                                                                            </script>
                                    </h2>
                                    <div class="box-icon">
                                    </div>
                                </div>
                                <div class="box-content">
                                    <?php echo $this->getMesseger(); ?>
                                <?php echo $this->layout()->content ?>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!--/fluid-row-->

                <hr>
                <div class="clear"></div>
                <br>
                <footer>
                    <p class="pull-left">&copy; <a href="#" target="_blank">Bitminds Consultors</a> 2013</p>
                    <p class="pull-right"><a href="#">WEBSOLPI</a></p>
                </footer>
            </div><!--/.fluid-container-->
            <?php echo $this->render('render/script-footer.phtml') ?>
<?php echo $this->headScript() ?>
    </body>
</html>