<h3><span class="glyphicon glyphicon-inbox"></span> Requerir Personal</h3>
<br/>
<form class="form-horizontal" role="form" method="post" action="">
    <input type="hidden" name="dataPersonal" id="dataPersonal" />
    <input type="hidden" name="empresaEnvio" id="empresaEnvio" />
    <fieldset>
        <div>
            <button  class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modalAgregarPersonal"><span class="glyphicon glyphicon-plus-sign"></span> Agregar Requerimiento de Personal
            </button>
        </div>
        <div class="clearfix"></div>
        <br/>
        <div class="dataTables_wrapper col-sm-8">
            <table id="tblPersonal" class="table table-striped table-bordered table-hover">
                <thead>
                <th width="5%">Nro</th>
                <th width="20%">Nombre del Puesto</th>
                <th width="30%">Principales Funciones</th>
                <th width="5%">Sueldo Promedio</th>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div class="clearfix"></div>
        <br/>
        <div class="col-sm-4">
            <div class="input-group">
                <span class="input-group-addon">
                    Enviar a Empresas de servicio de
                </span>
                <?php echo $this->form->getElement('categoria'); ?>
            </div>
        </div>
        <div class="col-sm-1">
            <button id="btnAgregarCategoria" class="btn btn-primary" title="Agregar" type="button">+</button>
        </div>

        <div class="col-sm-3">
            <div class="input-group">
                <span class="input-group-addon">
                    Fecha Límite de Recepción
                </span>
                <?php echo $this->form->getElement('fechaLimite'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <br/>
        <div id="dvCategoria" class="col-sm-3">

        </div>
        <div class="clearfix"></div>
        <br/>
        <br/>
        <div class="form-group">
            <div class="col-sm-offset-6">
                <a class="btn btn-default" href="<?php echo BASE_URL ?>/recursos-humanos/requerimiento">Cancelar</a>
                <button class="btn btn-primary" type="submit" id="btnEnviar" >Enviar</button>
            </div>
        </div>
    </fieldset>
</form>

<!-- Modal -->
<div class="modal fade" id="modalAgregarPersonal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Agregar Personal</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="frmAgregarPersonal" role="form" method="post" action="">
                    <fieldset>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Nombre
                                </span>
                                <?php echo $this->form->getElement('puesto'); ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Funciones
                                </span>
                                <?php echo $this->form->getElement('funcion'); ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-sm-5">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    Sueldo
                                </span>
                                <?php echo $this->form->getElement('sueldo'); ?>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                    </fieldset>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="submit" id="btnAgregarPersonal" class="btn btn-primary">Agregar</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->