<h3>Listado de Usuarios</h3>
<div class="box-content">
    <div>
        <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-usuario-nuevo')) { ?>
            <a class="btn btn-sm btn-primary" href="/administracion/usuario/nuevo"><span class="glyphicon glyphicon-plus-sign"></span> Agregar Nuevo Usuario
            </a>
        <?php } ?>
    </div>
    <br/>
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableUsuarios" class="table table-striped table-bordered bootstrap-datatable datatable dataTable" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th>Usuario</th>
            <th>Nombres</th>
            <th>Rol</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php
                foreach ($this->usuario as $usuario) {
                    ?>
                    <tr>
                        <td><?php echo $usuario['usuario_identity']; ?></td>
                        <td><?php echo $usuario['implicado_nombre'].' '.$usuario['implicado_apellido_materno'].' '.$usuario['implicado_apellido_paterno']; ?></td>
                        <td><?php echo $usuario['role_nombre']; ?></td>
                        <td><?php
                            if ($usuario['usuario_flag_activo'])
                                echo '<span class="label label-success">Activo</span>';
                            else
                                echo '<span class="label label-warning">Inactivo</span>';
                            ?>
                        </td>
                        <td>
                            <button class="ver btn btn-success btn-sm" usuario="<?php echo $usuario['usuario_id']; ?>"><span class="glyphicon glyphicon-zoom-in"></span> Ver</button>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-usuario-editar')) { ?>
                                <a class="btn btn-info btn-sm" href="/administracion/usuario/editar/id/<?php echo $usuario['usuario_id']; ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                            <?php } ?>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-usuario-activar')) { ?>
                                <?php if ($usuario['usuario_flag_activo']) { ?>
                                    <a class="btn btn-danger btn-sm" href="/administracion/usuario/activar/id/<?php echo $usuario['usuario_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                                <?php } else { ?>
                                    <a class="btn btn-warning btn-sm" href="/administracion/usuario/activar/id/<?php echo $usuario['usuario_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                                <?php } ?>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="verUsuarioModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Ver Usuario</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
