<div class="box-content" style="display: block;">
    <div>
        <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-organo-jurisdiccional-nuevo')) { ?>

            <a class="btn btn-small btn-primary" href="/administracion/organo-jurisdiccional/nuevo"><i class="icon-plus-sign icon-white"></i>Agregar Nuevo Organo Jurisdiccional</a>

        <?php } ?>
    </div>
    <br/>
    <?php if(count($this->listAll)>0){ ?>
    <div>
        <table id="tableAccesorios" class="table table-striped  table-hover dataTable">
            <thead>
            <th>Nombre</th>
            <th>distrito judicial</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php foreach ($this->listAll as $index): ?>
                    <tr>
                        <td><?php echo $index['organo_jurisdiccional_nombre']; ?></td>
                        <td>
                            <?php echo $index['distrito_judicial_nombre']; ?>
                        </td>
                        <td>
                            <?php if ($index['organo_jurisdiccional_flag_activo']) { ?>
                            <span class="label label-success">Activo</span>
                            <?php } else { ?>
                                <span class="label label-danger">Desactivado</span>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-organo-jurisdiccional-editar')) { ?>
                            <a class="btn btn-info" href="/administracion/organo-jurisdiccional/editar/id/<?php echo $index['organo_jurisdiccional_id']; ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                            <?php } ?>
   
                              
                              
                              
                              <?php if ($index['organo_jurisdiccional_flag_activo']) { ?>
                                    <a class="btn btn-danger btn-sm" href="/administracion/organo-jurisdiccional/activar/id/<?php echo $index['organo_jurisdiccional_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                                <?php } else { ?>
                                    <a class="btn btn-success btn-sm" href="/administracion/organo-jurisdiccional/activar/id/<?php echo $index['organo_jurisdiccional_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                                <?php } ?>
                        </td>
                    </tr>

                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php } else { ?>
    <div>No Hay datos registrados</div>
    <?php }  ?>
</div>
