<div class="box-content" style="display: block;">
    <h2>Agregar Nuevo Organo Jurisdiccional</h2>
    <hr>
    <div class="col-lg-6">
        <form action="" method="POST">
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Nombre: &nbsp;&nbsp;</span>
                    <?php echo $this->form->getElement('nombre'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-group">

                    <span class="input-group-addon">Distrito:</span>
                        <?php echo $this->form->getElement('distrito'); ?> 
                    

                </div>
            </div>
            <br>
            <div class="row">
                <button type="submit" class="btn btn-primary">Registrar</button>
                <a class="btn btn-default" href="/administracion/organo-jurisdiccional" >Cancelar</a>
            </div>    
        </form>
    </div>
</div>
