<h3>Listado de Materias</h3>
<div class="box-content" style="display: block;">
    <div>
        <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-materia-nuevo')) { ?>
        <a class="btn btn-sm btn-primary" href="/administracion/materia/nuevo"><span class="glyphicon glyphicon-plus-sign"></span>  Agregar nueva materia</a>
        <?php } ?>
    </div>
    <br/>
    
    <div>
        <table id="table" class="table table-striped  table-hover dataTable">
            <thead>
            <th>Materia</th>
            <th>Proceso</th>
            <th>Tipo Proceso</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php foreach ($this->listAll as $index): ?>
                    <tr>
                        <td><?php echo $index['materia_nombre']; ?></td>
                        <td><?php echo $index['proceso_nombre']; ?></td>
                        <td><?php echo $index['tipo_proceso_nombre']; ?></td>
                        <td>
                            <?php if ($index['proceso_flag_activo']) { ?>
                            <span class="label label-success">Activo</span>
                            <?php } else { ?>
                                <span class="label label-danger">Desactivado</span>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-proceso-editar')) { ?>
                            <a class="btn btn-info btn-sm" href="/administracion/materia/editar/id/<?php echo $index['materia_id']; ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                            <?php } ?>
                            <?php if ($this->acl->isAllowed($this->identity->role_nombre, 'administracion-proceso-activar')) { ?>
                            <?php if ($index['materia_flag_activo']) { ?>
                                    <a class="btn btn-danger btn-sm" href="/administracion/materia/activar/id/<?php echo $index['materia_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                                <?php } else { ?>
                                    <a class="btn btn-success btn-sm" href="/administracion/materia/activar/id/<?php echo $index['materia_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                                <?php } ?>
                            <?php } ?>
                        </td>
                    </tr>

                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>