<h3>Agregar Nueva Materia</h3>
<div class="box-content" style="display: block;">
    <hr>
    <div class="col-lg-6">
        <form action="" method="POST">
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Tipo Proceso: &nbsp;&nbsp;</span>
                    <?php echo $this->form->getElement('tipoProceso'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Proceso: &nbsp;&nbsp;</span>
                    <?php echo $this->form->getElement('proceso'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Nombre: &nbsp;&nbsp;</span>
                    <?php echo $this->form->getElement('nombre'); ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-group">
                    <span class="input-group-addon">Estado <?php echo $this->form->getElement('estado'); ?> :</span>
                    <input type="text" class="form-control" readonly="readonly">
                </div>
            </div>
            <br>
            <div class="row">
                <button type="submit" class="btn btn-primary">Registrar</button>
                <a class="btn btn-default" href="/administracion/materia" >Cancelar</a>
            </div>    
        </form>
    </div>
</div>
