<form class="form-horizontal" action="/perfil/editar" method="post">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="nombres">Tipo Documento: </label>
            <div class="controls">
                <?php  echo $this->form->getElement('tipoDocumento') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="nombres">Numero de Documento: </label>
            <div class="controls">
                <?php  echo $this->form->getElement('nroDocumento') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="nombres">Nombres: </label>
            <div class="controls">
                <?php  echo $this->form->getElement('nombres') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="apellidos">Apellidos: </label>
            <div class="controls">
                <?php  echo $this->form->getElement('apellidos') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="login">Usuario: </label>
            <div class="controls">
                <?php  echo $this->form->getElement('login') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="email">Correo</label>
            <div class="controls">
                <?php  echo $this->form->getElement('email') ?>
            </div>
        </div>

        <div class="form-actions">
            <button class="btn btn-primary" type="submit">Editar</button>
            <a class="btn" href="/default/perfil" type="reset">Cancelar</a>
        </div>
    </fieldset>
</form>