<h3>Perfil de Usuario</h3>
<p>Puede editar sus datos personales utilizando este formulario</p>

<form class="form-horizontal" role="form" method="post" action="">
    <fieldset>
        
        <div class="col-sm-7 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Nombres
                </span>
                <?php echo $this->form->getElement('nombres'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        
        <div class="col-sm-5 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Apellido Paterno
                </span>
                <?php echo $this->form->getElement('apellidoPaterno'); ?>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="input-group">
                <span class="input-group-addon">
                   Apellido Materno
                </span>
                <?php echo $this->form->getElement('apellidoMaterno'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        
        
        <div class="col-sm-5 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Teléfono
                </span>
                <?php echo $this->form->getElement('telefono'); ?>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="input-group">
                <span class="input-group-addon">
                   Celular
                </span>
                <?php echo $this->form->getElement('celular'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        
        
        <div class="col-sm-8 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Dirección
                </span>
                <?php echo $this->form->getElement('direccion'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        
        <div class="col-sm-5 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Correo Electrónico
                </span>
                <?php echo $this->form->getElement('email'); ?>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="input-group">
                <span class="input-group-addon">
                   Número Colegiatura
                </span>
                <?php echo $this->form->getElement('nroColegiatura'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        
        <div class="form-group">
            <div class="col-sm-8">
                <button class="btn btn-primary" type="submit">Actualizar Datos</button>
            </div>
        </div>
    </fieldset>
</form>
