<h2>Cambio de Contraseña</h2>
<p>Ingrese los siguientes datos para cambiar su contraseña</p>
<div class="col-md-6">
    <form class="form-horizontal" action="" method="post">
        <?php echo $this->form->getElement('usuario') ?>
        <div class="input-group margin-bottom-10">
            <span class="input-group-addon">Contraseña Anterior</span>
            <?php echo $this->form->getElement('contrasena') ?>
        </div>
        <div class="input-group margin-bottom-10">
            <span class="input-group-addon">Nueva Contraseña</span>
            <?php echo $this->form->getElement('contrasenaNueva') ?>
        </div>
        <div class="input-group margin-bottom-10">
            <span class="input-group-addon">Repetir Contraseña</span>
            <?php echo $this->form->getElement('contrasenaNueva2') ?>
        </div>

        <button class="btn btn-primary" type="submit">Actualizar Contraseña</button>
    </form>
</div>
