<h3>Trainer</h3>
<div class="col-sm-9">
    <div>
        <a class="btn btn-sm btn-primary" href="<?php echo BASE_URL ?>/administracion/trainer/nuevo"><span class="glyphicon glyphicon-plus-sign"></span> Nuevo Trainer
        </a>
    </div>
    <br/>
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableTrainer" class="table table-striped table-bordered bootstrap-datatable datatable dataTable" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php
                foreach ($this->trainer as $trainer) {
                    ?>
                    <tr>
                        <td><?php echo $trainer['trainer_nombres']; ?></td>
                        <td><?php echo $trainer['trainer_apellidos']; ?></td>
                        <td><?php
                            if ($trainer['swt_activo'])
                                echo '<span class="label label-success">Activo</span>';
                            else
                                echo '<span class="label label-warning">Finalizado</span>';
                            ?>
                        </td>
                        <td>
                            <a class="btn btn-info btn-sm" href="<?php echo BASE_URL; ?>/administracion/trainer/editar/id/<?php echo $trainer['trainer_id']; ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>

                            <?php if ($trainer['swt_activo']) { ?>
                                <a class="btn btn-danger btn-sm" href="<?php echo BASE_URL; ?>/administracion/trainer/activar/id/<?php echo $trainer['trainer_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                            <?php } else { ?>
                                <a class="btn btn-warning btn-sm" href="<?php echo BASE_URL; ?>/administracion/trainer/activar/id/<?php echo $trainer['trainer_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
