<h3>Mis Adquisiciones</h3>
<div class="col-sm-9">
    <!--    <div>
                <a class="btn btn-sm btn-primary" href="/logistica/adquisicion"><span class="glyphicon glyphicon-plus-sign"></span> Nueva Publicación
                </a>
        </div>-->
    <br/>
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableAdquisicion" class="table table-striped table-bordered bootstrap-datatable datatable dataTable" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th>Fecha Envío</th>
            <th>Tipo Adquisición</th>
            <th>Fecha Límite Cotización</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php
                foreach ($this->adquisicion as $adquisicion) {
                    $fechaEnvio = new Zend_Date($adquisicion['adquisicion_fecha_registro']);
                    $fechaLimite = new Zend_Date($adquisicion['adquisicion_fecha_limite']);
                    ?>
                    <tr>
                        <td><?php echo $fechaEnvio->get('dd-MM-YYYY'); ?></td>
                        <td><?php
                            if ($adquisicion['adquisicion_tipo'] == 1) {
                                echo "Producto";
                            } else {
                                echo "Servicio";
                            }
                            ?></td>
                        <td><?php echo $fechaLimite->get('dd-MM-YYYY'); ?></td>
                        <td>
                            <a class="btn btn-info btn-sm" href="/logistica/adquisicion/detalle/id/<?php echo $adquisicion['adquisicion_id']; ?>"><span class="glyphicon glyphicon-pencil"></span> Detalle</a>
                        </td>
                    </tr>
<?php } ?>
            </tbody>
        </table>
    </div>
</div>
