<div style="margin-top: 20px;font-size: 13px" class="container">
    <div class="col-md-12">
        <div class="col-md-7">
            <p>El Centro Empresarial CEMACC de Consultores ACC es la más completa plataforma de servicios empresariales del 
                Perú, creada para favorecer a la competitividad de las empresas usuarias permitiendo a éstas incrementar la 
                generación de valor y aumentar sus niveles de rentabilidad. El Centro Empresarial CEMACC cuenta con la 
                participación de las diversas organizaciones a nivel nacional, que presentan sus productos y servicios 
                atendiendo al empresario tanto en la sede Institucional de CEMACC, como de manera virtual en el Portal Web.</p>
            <h4><strong>Historia</strong></h4>
            <p>El 07 de septiembre del 2009 fue creada Consultores ACC, una empresa dedicada a brindar servicios de 
                Consultoría y Capacitación a diversas empresas del sector; desde su inicio se evidenció que la necesidad 
                era mayor, por lo que en el 2013 Consultores ACC apuesta en crear una plataforma mayor, el Centro 
                Empresarial, un sistema que permite una mejor interacción de los negocios y un soporte en el desarrollo 
                Organizacional, dirigidos a la pequeña, mediana y gran empresa, que desarrollen su actividad productiva 
                y/o comercial en cualquier sector productivo y a nivel nacional y a toda persona interesada a formar 
                empresa.</p>
            <p>CEMACC de Consultores ACC está asociado a RELAMCO "Reliability Asset Management Consulting” de Canadá, que 
                nos ha confiado su respaldo para auspiciar sus servicios en Perú y Sudamérica en los servicios de asesoría, 
                capacitación y formación.<br/> 
Talent Transcends, empresa especializada en la Gestión del Talento Humano, ha confiado en nuestra experiencia y la calidad 
de nuestros servicios para fortalecer los servicios que brinda el centro empresarial (Asesoría – Centro de Formación).
</p>
            <h4><strong>Misión</strong></h4>
            <p>Promover el desarrollo ofreciendo servicios integrados y sistematizados, contribuyendo a la mejora de la 
                competitividad de las empresas a través de nuestra plataforma CEMACC. </p>
            <h4><strong>Visión</strong></h4>
            <p>Ser el Centro Empresarial líder del país, reconocido por su capacidad de respuesta a las necesidades del 
                sector empresarial.</p>
        </div>

        <div class="col-md-5 publicidadMain thumbnail thumbMain">
            <img style="padding-top: 20px; padding-bottom: 20px;" src="<?php echo STATIC_URL . '/img/imagen-nosotros1.jpg'; ?>" alt="...">
        </div>
    </div>
</div>    
