<h3><span class="glyphicon glyphicon-inbox"></span> Editar Asesoría</h3>
<br/>
<form enctype='multipart/form-data' class="form-horizontal" role="form" method="post" action="">
    <?php echo $this->form->getElement('asesoria'); ?>
    <fieldset>
        <div class="col-sm-3 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Título
                </span>
                <?php echo $this->form->getElement('titulo'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-5 margin-bottom-10">
            <div class="input-group">
                <span class="input-group-addon">
                    Descripción
                </span>
                <?php echo $this->form->getElement('descripcion'); ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-3">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a class="btn btn-default" href="<?php echo BASE_URL; ?>/administracion/asesoria/">Cancelar</a>
        </div>
    </fieldset>
</form>
