<h3>Asesorías</h3>
<div class="col-sm-9">
    <div>
        <a class="btn btn-sm btn-primary" href="<?php echo BASE_URL ?>/administracion/asesoria/nuevo"><span class="glyphicon glyphicon-plus-sign"></span> Nueva Asesoría
        </a>
    </div>
    <br/>
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
        <table id="tableAsesoria" class="table table-striped table-bordered bootstrap-datatable datatable dataTable" aria-describedby="DataTables_Table_0_info">
            <thead>
            <th width="15%">Título</th>
            <th width="40%">Descripción Corta</th>
            <th>Fecha Registro</th>
            <th>Estado</th>
            <th>Acciones</th>
            </thead>
            <tbody>
                <?php
                foreach ($this->asesoria as $asesoria) {
                    $fechaRegistro = new Zend_Date($asesoria['asesoria_fecha_registro']);
                    $s = substr($asesoria['asesoria_descripcion'], 0, 150);
                    $des = substr($s, 0, strrpos($s, ' ')) . '...';
                    ?>
                    <tr>
                        <td><?php echo $asesoria['asesoria_titulo']; ?></td>
                        <td><?php echo $des; ?></td>        
                        <td><?php echo $fechaRegistro->get('dd-MM-YYYY'); ?></td>

                        <td><?php
                            if ($asesoria['swt_activo'])
                                echo '<span class="label label-success">Activo</span>';
                            else
                                echo '<span class="label label-warning">Finalizado</span>';
                            ?>
                        </td>
                        <td>
                            <a class="btn btn-info btn-sm" href="<?php echo BASE_URL; ?>/administracion/asesoria/editar/id/<?php echo $asesoria['asesoria_id']; ?>"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                            <?php if ($asesoria['swt_activo']) { ?>
                                <a class="btn btn-danger btn-sm" href="<?php echo BASE_URL; ?>/administracion/asesoria/activar/id/<?php echo $asesoria['asesoria_id']; ?>/flag/0"><span class="glyphicon glyphicon-ban-circle"></span> Desactivar</a>
                            <?php } else { ?>
                                <a class="btn btn-warning btn-sm" href="<?php echo BASE_URL; ?>/administracion/asesoria/activar/id/<?php echo $asesoria['asesoria_id']; ?>/flag/1"><span class="glyphicon glyphicon-ok"></span> Activar</a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
